// addSbtPlugin("com.dwijnand"      % "sbt-travisci"  % "1.1.0")
// addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo" % "0.7.0")
addSbtPlugin("com.lucidchart"    % "sbt-scalafmt"  % "1.10")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"       % "0.9.3")
addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "3.0.0")
addSbtPlugin("org.foundweekends" % "sbt-bintray"   % "0.5.1")
