addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"   % "0.6.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"         % "0.9.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"      % "1.8.0")
addSbtPlugin("me.lessis"         % "bintray-sbt"     % "0.3.0")
addSbtPlugin("org.scalariform"   % "sbt-scalariform" % "1.5.0")
