addSbtPlugin("com.dwijnand"      % "sbt-travisci"  % "1.0.0")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo" % "0.6.1")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"  % "0.6.6")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"       % "0.9.2")
addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "1.8.0")
addSbtPlugin("me.lessis"         % "bintray-sbt"   % "0.3.0")
